//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatPaPromyanAdmin.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_banner
    {
        public string id { get; set; }
        public string name1 { get; set; }
        public byte[] img1 { get; set; }
        public string name2 { get; set; }
        public byte[] img2 { get; set; }
        public string name3 { get; set; }
        public byte[] img3 { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string createBy { get; set; }
        public Nullable<System.DateTime> modifyDate { get; set; }
        public string modifyBy { get; set; }
    }
}
